# Generated by Django 4.2.3 on 2023-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='violin',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
