# Generated by Django 4.2.3 on 2023-10-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_guitar_image_alter_violin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drum',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
